# 异常处理

*异常的两个阶段：1.引起异常发生的错误  2.检测并处理异常

*当出现错误时，python自动引发异常；raise显式引发异常

## 异常类

#### 继承Python内置异常类实现自定义异常类

```
>>> class MyError(Exception):
        def __init__(self, value):
            self.value = value
        def __str__(self):
            return repr(self.value)

>>> try:
        raise MyError(2*2)
    except MyError as e:
        print('My exception occurred, value:', e.value)

My exception occurred, value: 4

/*
注: __str__()转化为字符串;  __repr__()打印、转换
*/
```

#### 创建基类，再创建多个派生类表示不同的异常

```
class Error(Exception):
    pass

class InputError(Error):
    def __init__(self, expression, message):
        self.expression = expression
        self.message = message

class TransitionError(Error):
    def __init__(self, previous, next, message):
        self.previous = previous
        self.next = next
        self.message = message
```

## 异常处理结构形式

#### try...except

try：可能出现异常的语句，except：处理异常

```
>>> while True:
	x = input('Please input:')
	try:
		x = int(x)
		print('You have input {0}'.format(x))
		break
	except Exception as e:
		print('Error.')
```

#### try...except...else

try捕获异常，执行except，没有则执行else

```
a_list = ['China', 'America', 'England', 'France']
while True:
	n = input('请输入字符串的序号')
    try:
        n = int(n)
	    print(a_list[n])
    except IndexError:
	    print('列表元素的下标越界，请重新输入字符串的序号')
    else:
	    break
```

```
for arg in sys.argv[1:]:
    try:
        f = open(arg, 'r')
    except IOError:
        print('cannot open', arg)
    else:
        print(arg, 'has', len(f.readlines()), 'lines')
        f.close()
```

#### 带有多个except的try结构

```
try:
    x=input('请输入被除数: ')
    y=input('请输入除数: ')
    z=float(x) / float(y)
except ZeroDivisionError:
    print('除数不能为零')
except TypeError:
    print('被除数和除数应为数值类型')
except NameError:
    print('变量不存在')
else:
    print(x, '/', y, '=', z)
```

#### try...except...finally

finally无论是否发生异常均执行

#### try...except...except...else...finally

## 断言与上下文管理

#### 断言

`assert expression[,reason]`

expression为真时，什么都不做；为假时，抛出异常

```
>>> a = 3
>>> b = 5
>>> try:
		assert a==b, 'a must be equal to b'
    except AssertionError as reason:
		print('%s:%s'%(reason.__class__.__name__, reason))
		
  AssertionError:a must be equal to b
```

#### 上下文管理语句

with自动关闭资源，可以在代码块执行完毕后还原进入该代码块时的现场

不论何种原因跳出with块，不论是否发生异常，总能保证文件被正确关闭，资源被正确释放

```
with open("myfile.txt") as f:
    for line in f:
        print(line, end="")
```

## 用sys模块回溯最后的异常

`tuple = sys.exc_info()`  

返回值tuple是一个三元组（<u>*异常类型*</u>type,<u>*异常信息/参数*</u>value/message,*<u>包含调用栈信息的对象</u>*traceback）

